name: Build with vcpkg

permissions:
  contents: read

on:
  push:
    branches:
      - dev
      - v*

    paths:
      - .github/workflows/build-vcpkg.yml
      - cmake/**
      - src/**
      - CMakeLists.txt
      - CMakePresets.json
      - vcpkg.json

  pull_request:
    paths:
      - .github/workflows/build-vcpkg.yml
      - cmake/**
      - src/**
      - CMakeLists.txt
      - CMakePresets.json
      - vcpkg.json

jobs:
  build-linux:
    name: Linux
    runs-on: ubuntu-latest

    env:
      CXX: g++-14
      VCPKG_BUILD_TYPE: release
      VCPKG_INSTALLED_DIR: ${{ github.workspace }}/vcpkg_installed/x64-linux
      VCPKG_DEFAULT_BINARY_CACHE: ${{ github.workspace }}/vcpkg_cache
      VCPKG_BINARY_SOURCES: clear;files,${{ github.workspace }}/vcpkg_cache,readwrite

    steps:
      - uses: actions/checkout@v6

      - name: Create vcpkg binary cache directory
        run: mkdir -p "${{ github.workspace }}/vcpkg_cache"
        shell: bash

      - name: Get latest CMake
        uses: lukka/get-cmake@latest

      - name: Cache vcpkg binary packages
        uses: actions/cache@v5
        with:
          path: ${{ github.workspace }}/vcpkg_cache
          key: vcpkg-linux-${{ hashFiles('vcpkg.json', 'CMakeLists.txt', '**/CMakeLists.txt', 'CMakePresets.json') }}
          restore-keys: |
            vcpkg-linux-

      - name: Run vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          doNotCache: false

      - name: Build with CMake
        uses: lukka/run-cmake@v10
        with:
          configurePreset: linux-release
          buildPreset: linux-release

      - name: Upload build logs
        uses: actions/upload-artifact@v7
        with:
          name: logs-linux-${{ github.sha }}
          path: ${{ github.workspace }}/vcpkg/buildtrees/**/*.log
        if: ${{ failure() }}

      - name: Upload artifact binary
        uses: actions/upload-artifact@v7
        with:
          name: tfs-linux-${{ github.sha }}
          path: ${{ github.workspace }}/build/linux-release/tfs

  build-windows:
    name: Windows
    runs-on: windows-latest

    env:
      VCPKG_BUILD_TYPE: release
      VCPKG_INSTALLED_DIR: ${{ github.workspace }}/vcpkg_installed/x64-windows-static-release
      VCPKG_DEFAULT_BINARY_CACHE: ${{ github.workspace }}/vcpkg_cache
      VCPKG_BINARY_SOURCES: clear;files,${{ github.workspace }}/vcpkg_cache,readwrite

    steps:
      - uses: actions/checkout@v6

      - name: Create vcpkg binary cache directory
        run: mkdir -p "${{ github.workspace }}/vcpkg_cache"
        shell: bash

      - name: Get latest CMake
        uses: lukka/get-cmake@latest

      - name: Cache vcpkg binary packages
        uses: actions/cache@v5
        with:
          path: ${{ github.workspace }}/vcpkg_cache
          key: vcpkg-windows-${{ hashFiles('vcpkg.json', 'CMakeLists.txt', '**/CMakeLists.txt', 'CMakePresets.json') }}
          restore-keys: |
            vcpkg-windows-

      - name: Run vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          doNotCache: false

      - name: Build with CMake
        uses: lukka/run-cmake@v10
        with:
          configurePreset: windows-release
          buildPreset: windows-release

      - name: Upload build logs
        uses: actions/upload-artifact@v7
        with:
          name: logs-windows-${{ github.sha }}
          path: ${{ github.workspace }}/vcpkg/buildtrees/**/*.log
        if: ${{ failure() }}

      - name: Upload artifact binary
        uses: actions/upload-artifact@v7
        with:
          name: tfs-windows-${{ github.sha }}
          path: |
            ${{ github.workspace }}/build/windows-release/tfs.exe
            ${{ github.workspace }}/build/windows-release/*.dll
